common/urls.py
from django.urls import path

from common.views import *

app_name='common'

urlpatterns = [
    path('', home, name='home'),
    path('grade/', grade, name='grade'),
    path('add-grade/', add_grade, name='add-grade'),
    path('delete-grade/<int:id>/', delete_grade, name='delete-grade'),
    path('update-grade/<int:id>/', update_grade, name='update-grade'),
    path('teacher/', teacher, name='teacher'),
    path('student/', student, name='student'),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
]

common/models.py
from django.db import models


class GradeBase(models.IntegerChoices):
    FIRST = 1, 'First'
    SECOND = 2, 'Second'
    THIRD = 3, 'Third'
    FOURTH = 4, 'Fourth'
    FIFTH = 5, 'Fifth'
    SIXTH = 6, 'Sixth'
    SEVENTH = 7, 'Seventh'
    EIGHTH = 8, 'Eighth'
    NINTH = 9, 'Ninth'
    TENTH = 10, 'Tenth'
    ELEVENTH = 11, 'Eleventh'


class Grade(models.Model):
    base = models.IntegerField(choices=GradeBase.choices, default=GradeBase.FIRST)
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.base} {self.name}'

common/views.py
from lib2to3.fixes.fix_input import context

from django.shortcuts import render, redirect

from common.models import Grade


def home(request):

    grade_count = Grade.objects.all().count()

    context = {
        'grade_count':grade_count
    }

    return render(request, 'home.html', context)


def grade(request):
    grades = Grade.objects.all().order_by('base', 'name')

    context = {
        'grades': grades,
    }

    return render(request, 'grade.html', context)


def add_grade(request):
    base = request.POST['base']
    name = request.POST['name']

    Grade.objects.create(
        base=base,
        name=name,
    )

    return redirect('common:grade')


def delete_grade(request, id):
    grade = Grade.objects.get(id=id)
    grade.delete()

    return redirect('common:grade')


def update_grade(request, id):
    if request.method == 'POST':

        grade = Grade.objects.get(id=id)
        grade.base = request.POST['base']
        grade.name = request.POST['name']
        grade.save()

        return redirect('common:grade')

    else:
        grade = Grade.objects.get(id=id)
        grades = Grade.objects.all().order_by('base', 'name')
        context = {
            "grade": grade,
            "grades": grades,
        }

        return render(request, 'grade.html', context)

def teacher(request):
    return render(request, 'teacher.html')


def student(request):
    return render(request, 'student.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
{% block title %}
{% endblock title %}
    </title>
</head>
<body>
    <a href="{% url 'common:home' %}">Home</a>
    |
    <a href="{% url 'common:grade' %}">Grade</a>
    |
    <a href="{% url 'common:teacher' %}">Teacher</a>
    |
    <a href="{% url 'common:student' %}">Student</a>

{% block content %}
{% endblock content %}

</body>
</html>

templates/grade.html
{% extends 'base.html' %}

{% block title %}
    Grade
{% endblock title %}

{% block content %}
    <h1>Grade</h1>

<form action="{% url 'common:add-grade' %}" method="post">
    {% csrf_token %}
    <select name="base">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
      <option value="11">11</option>
    </select>
    <input type="text" name="name" placeholder="Enter name">
    <input type="submit" value="Add">
</form>

<br>

<table border="1" width="300">
  <tr>
    <th>#</th>
    <th>Base</th>
    <th>Name</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
    {% for grade in grades %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ grade.base }}</td>
        <td>{{ grade.name }}</td>
        <td><a href="{% url 'common:update-grade' grade.id %}">Update</a></td>
        <td><a href="{% url 'common:delete-grade' grade.id %}">Delete</a></td>
      </tr>
    {% endfor %}

</table>
<br>
{% if grade %}
<form action="{% url 'common:update-grade' grade.id %}" method="post">
    {% csrf_token %}
    <select name="base">
      <option value="1" {% if grade.base == 1 %} selected {% endif %}>1</option>
      <option value="2" {% if grade.base == 2 %} selected {% endif %}>2</option>
      <option value="3" {% if grade.base == 3 %} selected {% endif %}>3</option>
      <option value="4" {% if grade.base == 4 %} selected {% endif %}>4</option>
      <option value="5" {% if grade.base == 5 %} selected {% endif %}>5</option>
      <option value="6" {% if grade.base == 6 %} selected {% endif %}>6</option>
      <option value="7" {% if grade.base == 7 %} selected {% endif %}>7</option>
      <option value="8" {% if grade.base == 8 %} selected {% endif %}>8</option>
      <option value="9" {% if grade.base == 9 %} selected {% endif %}>9</option>
      <option value="10" {% if grade.base == 10 %} selected {% endif %}>10</option>
      <option value="11" {% if grade.base == 11 %} selected {% endif %}>11</option>
    </select>
    <input type="text" name="name" placeholder="Enter name" value="{{ grade.name }}">
    <input type="submit" value="Update">
</form>
{% endif %}
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Title
{% endblock title %}

{% block content %}
    <h1> Home </h1>
    <h2>Sinflar soni : {{ grade_count }} ta</h2>
    <h2>O'qituvchilar soni : 0 ta</h2>
    <h2>O'quvchilar soni : 0 ta</h2>
{% endblock content %}

templates/student.html
{% extends 'base.html' %}

{% block title %}
    Student
{% endblock title %}

{% block content %}
    <h1>Student</h1>
{% endblock content %}

templates/teacher.html
{% extends 'base.html' %}

{% block title %}
    Teacher
{% endblock title %}

{% block content %}
    <h1>Teacher</h1>
{% endblock content %}